import type { FinishedTasksDynamics, TaskPeriod, TaskSummaryItem } from './types';
import type { ProjectTaskItem } from './types';

export const taskSummaryMock: TaskSummaryItem[] = [
  {
    id: 'completed',
    title: 'Готово',
    amount: 8,
    trendData: [6, 8, 7, 9, 10, 9, 11],
    lineColor: '#5051F9',
  },
  {
    id: 'new',
    title: 'Новое',
    amount: 10,
    trendData: [9, 7, 8, 6, 7, 5, 6],
    lineColor: '#1EA7FF',
  },
  {
    id: 'projects',
    title: 'Готовые проекты',
    amount: 10,
    trendData: [3, 4, 5, 4, 6, 5, 7],
    lineColor: '#FF614C',
  },
];

export const finishedTasksDynamicsMock: Record<TaskPeriod, FinishedTasksDynamics> = {
  day: {
    labels: ['00:00', '04:00', '08:00', '12:00', '16:00', '20:00', '24:00'],
    purple: [20, 35, 110, 170, 140, 190, 120],
    blue: [15, 30, 80, 120, 90, 145, 100],
  },
  week: {
    labels: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
    purple: [160, 220, 190, 280, 310, 240, 200],
    blue: [120, 170, 140, 210, 190, 160, 130],
  },
  month: {
    labels: ['Май', 'Июнь', 'Июль', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек', 'Янв', 'Фев', 'Март', 'Апр'],
    purple: [90, 120, 110, 380, 260, 170, 220, 130, 175, 325, 285, 160],
    blue: [50, 200, 230, 305, 190, 225, 35, 55, 65, 70, 155, 120],
  },
};

export const projectTasksMock: ProjectTaskItem[] = [
  {
    id: 't-1',
    projectId: '1',
    title: 'Сформировать структуру диплома',
    status: 'queue',
    category: 'Планирование',
    categoryColor: '#F57644',
    description: 'Содержание ВКР',
    dateLabel: 'Apr 18, 2026',
    subtasks: [
      { id: 'st-1-1', title: 'Составить план главы 1', isDone: false },
      { id: 'st-1-2', title: 'Составить план главы 2', isDone: false },
      { id: 'st-1-3', title: 'Составить план главы 3', isDone: false },
      { id: 'st-1-4', title: 'Добавить структуру приложений', isDone: false },
      { id: 'st-1-5', title: 'Согласовать структуру с руководителем', isDone: false },
      { id: 'st-1-6', title: 'Внести правки', isDone: false },
    ],
  },
  {
    id: 't-2',
    projectId: '1',
    title: 'Разработать ER-диаграмму данных',
    status: 'in-progress',
    category: 'Исследование',
    categoryColor: '#2EA3E6',
    description: 'Содержание ВКР',
    dateLabel: 'Apr 20, 2026',
    subtasks: [
      { id: 'st-2-1', title: 'Определить сущности', isDone: true },
      { id: 'st-2-2', title: 'Определить атрибуты', isDone: true },
      { id: 'st-2-3', title: 'Связи между сущностями', isDone: true },
      { id: 'st-2-4', title: 'Нормализация', isDone: false },
      { id: 'st-2-5', title: 'Проверка ограничений', isDone: false },
      { id: 'st-2-6', title: 'Документация ER', isDone: false },
      { id: 'st-2-7', title: 'Ревью схемы', isDone: false },
      { id: 'st-2-8', title: 'Финальные правки', isDone: false },
    ],
  },
  {
    id: 't-3',
    projectId: '1',
    title: 'Подготовить прототип интерфейса',
    status: 'review',
    category: 'Дизайн',
    categoryColor: '#5051F9',
    description: 'Содержание ВКР',
    dateLabel: 'Apr 21, 2026',
    cover: 'blue',
  },
  {
    id: 't-4',
    projectId: '1',
    title: 'Описать результаты тестирования',
    status: 'done',
    category: 'Контент',
    categoryColor: '#F59E0B',
    description: 'Содержание ВКР',
    dateLabel: 'Apr 22, 2026',
    subtasks: [
      { id: 'st-4-1', title: 'Собрать метрики', isDone: true },
      { id: 'st-4-2', title: 'Описать сценарии', isDone: true },
      { id: 'st-4-3', title: 'Описать среду тестирования', isDone: true },
      { id: 'st-4-4', title: 'Провести функциональные тесты', isDone: true },
      { id: 'st-4-5', title: 'Провести нагрузочные тесты', isDone: true },
      { id: 'st-4-6', title: 'Сделать выводы', isDone: true },
      { id: 'st-4-7', title: 'Подготовить диаграммы', isDone: true },
      { id: 'st-4-8', title: 'Финальная редактура', isDone: true },
    ],
  },

  {
    id: 't-5',
    projectId: '2',
    title: 'Создать руководство по стилю',
    status: 'queue',
    category: 'Дизайн',
    categoryColor: '#5051F9',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 20, 2026',
    checklistDone: 0,
    checklistTotal: 8,
    assignees: ['S', 'A'],
    cover: 'blue',
  },
  {
    id: 't-6',
    projectId: '2',
    title: 'Копирайтинг',
    status: 'queue',
    category: 'Исследование',
    categoryColor: '#2EA3E6',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
    assignees: ['S', 'D'],
  },
  {
    id: 't-7',
    projectId: '2',
    title: 'Обновить лист требований',
    status: 'queue',
    category: 'Планирование',
    categoryColor: '#F57644',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
  },
  {
    id: 't-8',
    projectId: '2',
    title: 'Аудит архитектуры',
    status: 'in-progress',
    category: 'Исследование',
    categoryColor: '#2EA3E6',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
  },
  {
    id: 't-9',
    projectId: '2',
    title: 'Обновить документацию',
    status: 'in-progress',
    category: 'Контент',
    categoryColor: '#F59E0B',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 30, 2026',
    checklistDone: 0,
    checklistTotal: 8,
    cover: 'violet',
  },
  {
    id: 't-10',
    projectId: '2',
    title: 'Оценка качества',
    status: 'in-progress',
    category: 'Исследование',
    categoryColor: '#2EA3E6',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
  },
  {
    id: 't-11',
    projectId: '2',
    title: 'Чеклист функционала',
    status: 'review',
    category: 'Planning',
    categoryColor: '#F57644',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
  },
  {
    id: 't-12',
    projectId: '2',
    title: 'Оценка требований',
    status: 'review',
    category: 'Исследование',
    categoryColor: '#2EA3E6',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
  },
  {
    id: 't-13',
    projectId: '2',
    title: 'Текстовый контент',
    status: 'review',
    category: 'Дизайн',
    categoryColor: '#5051F9',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
    cover: 'orange',
  },
  {
    id: 't-14',
    projectId: '2',
    title: 'Дизайн-система',
    status: 'done',
    category: 'Контент',
    categoryColor: '#F59E0B',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
    cover: 'blue',
  },
  {
    id: 't-15',
    projectId: '2',
    title: 'UI десятка',
    status: 'done',
    category: 'Дизайн',
    categoryColor: '#5051F9',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
    checklistDone: 0,
    checklistTotal: 8,
  },
  {
    id: 't-16',
    projectId: '2',
    title: 'Чеклист результатов',
    status: 'done',
    category: 'Контент',
    categoryColor: '#F59E0B',
    description: 'Содержание для e-commerce',
    dateLabel: 'Apr 21, 2026',
  },
];
